[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
\.git
| \.hg
| \.mypy_cache
IUCr macros version 2.1.17: 2023/10/19
45
| \.tox
| \.venv
| \.rst
| \.txt
| _build
| buck-out
| build
| dist
| blib2to3
| tests/data
)/
'''