name: CI

on:
  push:
    branches:
      - main
  release:
    types:
      - prereleased
      - published
  workflow_dispatch:

jobs:
  matrix-coverage:
    uses: scikit-package/release-scripts/.github/workflows/_matrix-and-codecov-on-merge-to-main.yml@v0
    with:
      project: diffpy.srxplanar
      c_extension: false
      headless: false
      python_version: 3.13
      run: |
        pip install diffpy.srxconfutils

    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
