name: Tests on PR

on:
  pull_request:
  workflow_dispatch:

jobs:
  tests-on-pr:
    uses: scikit-package/release-scripts/.github/workflows/_tests-on-pr.yml@v0
    with:
      project: diffpy.srxplanar
      c_extension: false
      headless: false
      python_version: "3.13"
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
